version: '2'
services:
    frontend-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/frontend/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=frontend
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
